language: python
python:
  - 2.7
services:
  - mongodb
before_install:
    - sudo apt-get install python-dev
    - sudo apt-get install g++
    - sudo apt-get install libssl0.9.8
    - wget https://github.com/SuperCowPowers/data/raw/master/packages/Bro-2.2-Linux-x86_64_flex.deb
    - sudo dpkg -i Bro-2.2-Linux-x86_64_flex.deb
    - export PATH=/opt/bro/bin:$PATH
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install git+https://github.com/newbrough/coverage.git
script:
  ./runtests
after_success:
  coveralls
